### PR TITLE
Anatomogram software release notes

### PR DESCRIPTION
**Pull request by pcm32**
This PR adds SC release notes for the much anticipated anatomograms release.

### CODE REVIEW

**Comment by sfexova** [comment]
Hi @pcm32 - looks good, I actually thought we weren't releasing the placenta because I didn't see an anatomogram here: https://wwwdev.ebi.ac.uk/gxa/sc/experiments/E-MTAB-6701/results/tsne but now I see we have it with the other experiment - https://wwwdev.ebi.ac.uk/gxa/sc/experiments/E-MTAB-6678/results/tsne. Please do not add the liver example - it's quite obvious that it's broken and missing a lot of cell types, so I'd keep a low profile about that one until we can fix it. I'd use the placenta (https://wwwdev.ebi.ac.uk/gxa/sc/experiments/E-MTAB-6678/results/tsne) instead, that looks much better

**Comment by sfexova** [comment]
oh and I don't think we have any 'valid' datasets for kidney, so I'd leave that one out - I believe there's just the one experiment with kidney anatomogram that I reported yesterday and it shouldn't actually have it. I'll double check all the experiments and send you the exact number of the ones with anatomograms

**Comment by sfexova** [comment]
Hi @pcm32 so I went through the experiments and by my count we have six, which do and should have (=are eligible) an anatomogram: pancreas 3, lung 1, liver 1, placenta 1. So I'd change this bit to:
'New interactive human organ anatomograms for lung, pancreas, liver and placenta allow users to explore expression of top marker genes for individual cell types and visualize these different cell types in the broader structural context within each tissue/organ. Currently 6 experiments in Single Cell Expression Atlas, that have the required level of annotation, include anatomograms.'

**Comment by pcm32** [comment]
@sfexova this is the count of experiments I have:

Pancreas

1.- https://www.ebi.ac.uk/gxa/sc/experiments/E-GEOD-81547/results/anatomogram
2.- https://www.ebi.ac.uk/gxa/sc/experiments/E-MTAB-5061/results/anatomogram
3.- https://www.ebi.ac.uk/gxa/sc/experiments/E-GEOD-81608/results/anatomogram
4.- https://www.ebi.ac.uk/gxa/sc/experiments/E-ENAD-27/results/anatomogram
5.- https://www.ebi.ac.uk/gxa/sc/experiments/E-GEOD-83139/results/anatomogram

Liver:
6.- https://www.ebi.ac.uk/gxa/sc/experiments/E-HCAD-9/results/anatomogram
(hidden) https://www.ebi.ac.uk/gxa/sc/experiments/E-GEOD-130473/results/anatomogram

Lung:
7.- https://www.ebi.ac.uk/gxa/sc/experiments/E-GEOD-130148/results/anatomogram
(hidden) https://www.ebi.ac.uk/gxa/sc/experiments/E-HCAD-8/results/anatomogram
8.- https://www.ebi.ac.uk/gxa/sc/experiments/E-HCAD-1/results/anatomogram
(hidden) https://www.ebi.ac.uk/gxa/sc/experiments/E-GEOD-86618/results/anatomogram
(hidden) https://www.ebi.ac.uk/gxa/sc/experiments/E-CURD-11/results/anatomogram
(hidden) https://www.ebi.ac.uk/gxa/sc/experiments/E-MTAB-6308/results/anatomogram

Kidney:
(hidden) https://www.ebi.ac.uk/gxa/sc/experiments/E-HCAD-10/results/anatomogram
(hidden) https://www.ebi.ac.uk/gxa/sc/experiments/E-CURD-10/results/anatomogram
(hidden no cell types) https://www.ebi.ac.uk/gxa/sc/experiments/E-MTAB-7407/results/anatomogram

Placenta:
9.- https://www.ebi.ac.uk/gxa/sc/experiments/E-MTAB-6678/results/anatomogram
(hidden - should be shown) https://www.ebi.ac.uk/gxa/sc/experiments/E-MTAB-6701/results/anatomogram


So I count 9 experiments. Would you be happy with that number?

**Comment by sfexova** [comment]
Ah right - I didn't find all of the pancreas ones and one for the lung too (I was just going through browse the exp and searching with keywords)- yes, you're right 9 - thanks!

**Comment by pcm32** [comment]
> I really would remove the kidney from the description - it's only there by error - and also maybe slightly change the text as suggested in my previous comment, if you're ok with my version. I can change it in the file and make a commit myself if you prefer @pcm32

Sorry, I hadn't noticed that kidney was still there, I thought I had removed it earlier. Gone now.

**Comment by pcm32** [comment]
I wonder if you want to put a link to the anatomograms component @alfonsomunozpomer ? since we said that that could be made public once the anatomograms would be released on SC.

**Comment by ngeorgeebi** [comment]
just reading through the comments! @sfexova i think you'd know best what datasets we have but I agree with the comments about liver - there's a huge disconnect between what should be shown and what is shown.

**Comment by sfexova** [comment]
> just reading through the comments! @sfexova i think you'd know best what datasets we have but I agree with the comments about liver - there's a huge disconnect between what should be shown and what is shown.

yes, I know. I'm keeping quiet about it in the news item etc (with irene's permission), so we do not draw attention to it too much

**Comment by pcm32** [comment]
Ok, given that there are no more comments/observations on this, I'll merge it. You can always PR again and modify if needed.

**Pull request merged**
