### PR TITLE
GXA data statistics and release notes for rel 34

### PR DESCRIPTION
**Pull request by suhaibMo**
- Ensembl version - 99
- Ensembl Genome version - 46
- WormBase Parasite version - 14

### CODE REVIEW

**Comment by pcm32** [comment]
Thanks @suhaibMo, lets wait for @alfonsomunozpomer and co to add their software features before merging please.

**Comment by pcm32** [comment]
@suhaibMo this looks good to me, provided that numbers are up to date. If you are happy with it, can you remove the WIP and ask the curators to review it? Web team will add features later, so we will just merge with the data update.

**Review by pcm32 — APPROVED** [review]

**Review by anjaf — APPROVED** [review]
Looks good to me

**Comment by suhaibMo** [comment]
Thanks all for the review. The numbers seems alright. 
Note: For proteomics study, the ones not in prod or dev have not been included ```E-PROT-2, E-PROT-4, E-PROT-7, E-PROT-8, E-PROT-12, E-PROT-14, E-PROT-15``` Which means proteins studies remain same as we added new ones breaking even.

**Comment by pcm32** [comment]
Thanks @suhaibMo !

**Pull request merged**
